<?php

namespace Backend\Controller;

use Cake\Datasource\Exception\MissingModelException;
use Cake\ORM\Table;

/**
 * Class JsTreeAwareTrait
 *
 * @package Backend\Controller
 */
trait JsTreeAwareTrait
{
    /**
     * Tree node data formatted for jsTree
     *
     * Expected format of the node (there are no required fields)
     * {
     *  id          : "string" // will be autogenerated if omitted
     *  text        : "string" // node text
     *  icon        : "string" // string for custom
     *  state       : {
     *  opened      : boolean  // is the node open
     *  disabled    : boolean  // is the node disabled
     *  selected    : boolean  // is the node selected
     * },
     *  children    : []  // array of strings or objects
     *  li_attr     : {}  // attributes for the generated LI node
     *  a_attr      : {}  // attributes for the generated A node
     * }
     * @link https://jstree.com
     *
     * @param Table $Model
     */
    public function treeData($Model = null)
    {
        $this->autoRender = false;
        $this->viewBuilder()->setClassName('Json');

        $Model = null;
        if ($Model === null && method_exists($this, 'model')) {
            $Model = $this->model();
        } elseif (isset($this->modelClass)) {
            list(, $alias) = pluginSplit($this->modelClass, true);

            if (!isset($this->{$alias})) {
                throw new MissingModelException("Primary model not loaded");
            }

            $Model = $this->{$alias};
        }

        if ($Model === null) {
            throw new MissingModelException("No primary model found");
        }

        if (!$Model->behaviors()->has('JsTree')) {
            $Model->behaviors()->load('Banana.JsTree');
        }

        $jsTree = $Model->getJsTree();

        $this->set('jsTree', $jsTree);
        $this->set('_serialize', 'jsTree');
        $this->render();
    }

    /**
     * Tree node view action
     *
     * @TODO Filter Ajax requests
     */
    public function treeView()
    {
        $id = $this->request->getQuery('id');
        $this->setAction('view', $id);
    }
}
